# 예외 처리
### 왜 예외 처리를 해야 하는가?
항상 올바른 Input이 있을 수는 없고 예상치 못한 로직 에러가 발생하거나 외부 요인으로 인해 코드 실행에 지장이 있을 수 있다.  

예외 처리를 통해 이런 예외 상황이 발생했을 때 코드의 이상작동을 미연에 방지하기 위함. 

### 예외 처리 구조
```python
try:
  # 에러가 발생할 수도 있는 코드를 입력하는 블럭.
except ValueError:
  # 에러가 발생했을 경우 처리하는 코드를 입력하는 블럭.
  # except에 예외 유형을 지정하면 해당하는 예외만 처리한다.
  # except는 연달아 여러번 사용할 수 있다.
else:
  # 에러가 발생하지 않았을 경우 처리하는 코드를 입력하는 블럭.
finally:
  # 항상 작동하는 코드를 입력하는 블럭.
```

### 예외를 발생시키는 법
raise를 통해서 에러를 발생시킬 수 있고, try except문법을 이용하면 발생시킨 에러를 except 내부에서 처리할 수 있다.
```python
try:
  raise ValueError("ValueError 발생")
except ValueError as e:
  print("예외 처리. " + e)
  # 예외 처리. ValueError 발생
```

### 예외 처리의 계층구조
예외 처리는 계층구조로 되어 있으며 가장 최상단에는 Exception이 존재한다.  
except Exception을 사용하면 모든 예외를 처리할 수 있지만, 각 예외 유형별 처리가 필요한 경우는 세부 예외처리를 이용한다.

### 커스텀 예외 처리 클래스 생성
내장된 예외 유형 말고도 사용자가 원하는 예외 클래스를 구성할 수 있다.  
Exception을 상속받아서 클래스를 구성하면 내장 예외 유형처럼 사용 할 수 있다.
```python
class CustomError(Exception):
  def __init__(self):
	  super.__init("custom error")
    
try:
  raise CustomError("CustomError 발생")
except CustomError as e:
  print("예외 처리. " + e)
  # 예외 처리. CustomError 발생
```
